### ISSUE TITLE
chmod of mvnw causes GitLab CI build to fail

### ISSUE THREAD

**Issue by cz4rny** [paketo-buildpacks/maven#150]
## What happened?

 * What were you attempting to do?

I was trying to build a vanilla Spring Boot Initializr demo application with Maven using a basic `creator` based GitLab job:

```yaml
stages:
  - build

default:
  tags:
    - linux
    - x86_64 
 
build-image:
  stage: build
  image: paketobuildpacks/builder:base
  # Access to GitLab Container Registry for Paketo lifecycle
  before_script:
    - mkdir ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" >> ~/.docker/config.json
  script:
    - /cnb/lifecycle/creator
      -app=.
      $CI_REGISTRY_IMAGE:latest
```

* What did you expect to happen?

Buildpacks to discover Spring Boot & maven app, build the OCI image and push it to my project's Container Registry.

* What was the actual behavior? Please provide log output, if possible.

The job failed while trying to add an executable flag (`chmod +x`) to the `mvnw` binary. Probably due to dropping privileges to normal user which lost write access to the directory.

```
Paketo Maven Buildpack 6.5.2
  https://github.com/paketo-buildpacks/maven
  Build Configuration:
    $BP_MAVEN_BUILD_ARGUMENTS  -Dmaven.test.skip=true --no-transfer-progress package  the arguments to pass to Maven
    $BP_MAVEN_BUILT_ARTIFACT   target/*.[ejw]ar                                       the built application artifact explicitly.  Supersedes $BP_MAVEN_BUILT_MODULE
    $BP_MAVEN_BUILT_MODULE                                                            the module to find application artifact in
    $BP_MAVEN_DAEMON_ENABLED   false                                                  use maven daemon
    $BP_MAVEN_POM_FILE         pom.xml                                                the location of the main pom.xml file, relative to the application root
Paketo Maven Buildpack 6.5.2
  unable to chmod /builds/librarians/developer-experience/test-for-eks/mvnw
  chmod /builds/librarians/developer-experience/test-for-eks/mvnw: operation not permitted
ERROR: failed to build: exit status 1
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

## Build Configuration
* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
  
  GitLab 14.10.1 calling the `creator` script from the `paketobuildpacks/builder@sha256:eae726051f9e96855cdb8a393bc69eeb1dfc9670b4b59116eb5683f54191635a` image

* What buildpacks are you using? Please include versions.

What got auto-discovered, as I've provided no suggestions to the `creator` script:

```
Warning: Not restoring or caching layer data, no cache flag specified.
===> DETECTING
9 of 24 buildpacks participating
paketo-buildpacks/ca-certificates   3.2.2
paketo-buildpacks/bellsoft-liberica 9.3.4
paketo-buildpacks/syft              1.11.0
paketo-buildpacks/maven             6.5.2
paketo-buildpacks/executable-jar    6.2.3
paketo-buildpacks/apache-tomcat     7.3.3
paketo-buildpacks/liberty           1.1.0
paketo-buildpacks/dist-zip          5.2.3
paketo-buildpacks/spring-boot       5.10.0
```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
  
  ```Using docker image sha256:19ddf409a6cced9fb6447bdd1c23bc1ba6a47413f3b2915335ac7e6aaed0b87e for paketobuildpacks/builder:base with digest paketobuildpacks/builder@sha256:eae726051f9e96855cdb8a393bc69eeb1dfc9670b4b59116eb5683f54191635```

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
  
There is nothing specific about that. Plain Spring Boot Initializr app, so almost no source code, no `buildpack.yml`, just `pom.xml` and `mvnw` in repo.

## Checklist
* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.
